"cellDia"= 21.55mm
"cellRad"= "cellDia" / 2
"cellGap"= 1.2mm
"holeTol"= .1mm
"holeDia"= "cellDia" + 2 * "holeTol"
"cellAngle"= 30deg
"groupHeight"= 13 * ( ( "holeDia" + "cellGap" ) * cos ( "cellAngle" ) ) + "holeDia"
"groupWidth"= "holeRad" * 7 + "cellGap" * 2.5
"senseSpace"= 12mm
"outEdge"= 0mm
"topEdge"= 15mm
"bottomEdge"= 10mm
"blockWidth"= ( 2 * "outEdge" ) + ( 2 * "groupWidth" ) + "senseSpace" - 7.75
"blockHeight"= "topEdge" + "bottomEdge" + "groupHeight"
"cellLinSpace"= "holeDia" + "cellGap"
"D2@Cell Block Sketch"= "blockHeight"
"standThickness"= 7.5mm
"blockThickness"= 10mm
"railThickness"= "blockThickness" + "standThickness"
"railWidth"= 9mm
"boltSpacing"= 50mm
"D1@Main Body" = "blockThickness"
"D1@Cell Block Sketch"="blockWidth"
"D1@Cell Hole Pattern" = "cellAngle"
"D2@Cell Hole Pattern" = "holeDia" + "cellGap"
"D3@Cell Hole Pattern" = "holeDia"
"holeRad"= "holeDia" / 2
"D8@Cell Hole Pattern" = 2 *  ( "holeDia" + "cellGap" )  * cos ( "cellAngle" ) 
"D9@Cell Hole Pattern" = "holeDia" + "cellGap"
"D10@Cell Hole Pattern" = "holeDia"
"D11@Cell Hole Pattern" = "holeDia" + "cellGap"
"D12@Cell Hole Pattern" = "bottomEdge"
"D4@Cell Hole Pattern" = "bottomEdge"
"D14@Cell Hole Pattern" = "cellAngle"
"D18@Cell Hole Pattern" = "D8@Cell Hole Pattern"
"D17@Cell Hole Pattern" = "D9@Cell Hole Pattern"
"nippleDiameter"=14
"D19@Cell Hole Pattern" = "nippleDiameter"
"D20@Cell Hole Pattern" = "D19@Cell Hole Pattern"
"D1@Sketch3"="railWidth"
"railHieght"=286.017
"railHeight"=290
"D1@Rail Body"="railThickness"
"sideBoltHoleDia"=4
"`0"=15
"D1@Bonding Cutout Sketch" = "holeDia"
"D2@Bonding Cutout Sketch" = "holeDia"
"nippleRadius"=7
"D3@Bonding Cutout Sketch" = "nippleRadius"
"D4@Bonding Cutout Sketch" = "nippleRadius"
"D9@Bonding Cutout Sketch" = "nippleRadius"
"D10@Bonding Cutout Sketch" = "nippleRadius"
"D18@Bonding Cutout Sketch" = 2 *  ( "holeDia" + "cellGap" )  * cos ( "cellAngle" ) 
"D17@Bonding Cutout Sketch" = "holeDia" + "cellGap"
"D21@Bonding Cutout Sketch" = "holeDia" + "cellGap"
"D22@Bonding Cutout Sketch" = 2 *  ( "holeDia" + "cellGap" )  * cos ( "cellAngle" ) 
"D3@Sketch14"=2* ("holeDia" + "cellGap") * cos("cellAngle")
"D5@Sketch14"=2*("holeDia" + "cellGap") * cos("cellAngle")
"D8@Sketch14"=2 * ("cellGap" + "holeDia") * cos("cellAngle")
"D10@Sketch14"="D8@Sketch14"
"D1@Side Bolt Reference Sketch"="D2@Side Bolt Reference Sketch"
"D3@Side Bolt Reference Sketch"="D2@Side Bolt Reference Sketch"
"D5@Cell Hole Pattern"="holeRad"+"outEdge"
"D13@Cell Hole Pattern"="D5@Cell Hole Pattern"
"BMSbackplate"= 3mm
"D4@Sketch24"="D3@Sketch24"
"D4@Sketch27"= 2 * ("holeDia" + "cellGap") * cos("cellAngle")
